### PR TITLE
Do not read Info block if it does not exist

### PR DESCRIPTION
**Pull request by bmordue**
Fixes issue described here: https://github.com/OpenAPITools/openapi-generator/issues/177

### CODE REVIEW

**Comment by jmini** [comment]
This is a great patch! Thank you a lot for the investigation and the fix.

---

Can you submit it also against `swagger-api/swagger-parser`?

We are not really using this fork for now.

**Comment by jmini** [comment]
Or if you agree I will present it in the official project after having added a unit test for your use case.

**Comment by bmordue** [comment]
Hi @jmini, I just opened the PR there: https://github.com/swagger-api/swagger-parser/pull/753
Please feel free to add a test to that branch, or to pick the commit into your own branch.

**Comment by jmini** [comment]
I do not have the right to push anything on your `no-info-block-oas3` branch, but I have created 9d0094a99c2a4a11e9fb4b6d8c40872e03fe36cc on top of https://github.com/bmordue/swagger-parser/commit/4a8e21846720edce0b7246ebc08182669998e242

Can you:
1) give me push right to your branch (I am not maintainer of the other project)
2) rebase (fast-forward) your `no-info-block-oas3` on top of `OpenAPITools/no-info-block-oas3`

___
If you edit this PR, are you able to change the branches to:

> @bmordue wants to merge 1 commit into `OpenAPITools:2.0-OpenAPITools` from `bmordue:no-info-block-oas3`

Current is:
> @bmordue wants to merge 1 commit into `OpenAPITools:2.0-OpenAPITools` from `bmordue:no-info-block`

Maybe this will give me write right as maintainer of this project.

**Comment by bmordue** [comment]
@jmini Do we still want this PR open, or shall I close it in favour of this one: https://github.com/swagger-api/swagger-parser/pull/753 ?

**Comment by jmini** [comment]
Leave it open, we like to have the commits our community is interested in our `2.0-OpenAPITools` branch. Just in case we need to release it ourself.

More background: https://github.com/OpenAPITools/openapi-generator/issues/68

**Pull request merged**
